// User action types
export const UserTypes = {
	FETCH_USERS: 'FETCH_USERS',
	RECEIVE_USERS: 'RECEIVE_USERS',
	ADD_USER: 'ADD_USER'
}
// Score action types
export const ScoreTypes = {
	FETCH_SCORES: 'FETCH_SCORES',
	RECEIVE_SCORES: 'RECEIVE_SCORES',
	ADD_SCORE: 'ADD_SCORE',
	RECEIVE_SCORES_BY_PLAYERS: 'RECEIVE_SCORES_BY_PLAYERS',
	FETCH_SCORES_BY_PLAYERS: 'FETCH_SCORES_BY_PLAYERS'
}